# Generated by Django 2.1.2 on 2018-10-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181025_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True, verbose_name='HashTag link'),
        ),
    ]
